# This is a basic workflow to build and push an image to ACR
name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IMAGE_NAME: hello-world-app
  APP_MANIFEST_PATH: app-manifests
  MANIFEST_BRANCH : manifest-repo

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Connect to Azure Container registry (ACR)
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.SP_USERNAME }} 
          password: ${{ secrets.SP_PASSWORD }}
      
      # Container build and push to a Azure Container registry (ACR)
      - run: |
          docker build . -t ${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
  
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - uses: actions/checkout@v2
  #       name: checkout manifest branch
  #       with:
  #         ref: ${{ env.MANIFEST_BRANCH }}

  #     - name: Kustomize edit image
  #       run: |
  #         cd ${{ env.APP_MANIFEST_PATH }}
  #         kustomize edit set image hello-world=${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
  #         cat kustomization.yaml

  #     - name: Commit kustomization.yaml
  #       run: |
  #         git config user.name github-actions
  #         git config user.email github-actions@github.com
  #         git add .
  #         git commit -m "github actions workflow - updating image tag to ${{ github.sha }}"
  #         git push origin ${{ env.MANIFEST_BRANCH }}