name: Linux Container Node Workflow

on:
  push:
    branches:
      - main

env:
  appName: hello-world-node-express-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: ${{secrets.ACR_LOGIN_SERVER}}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t ${{secrets.ACR_LOGIN_SERVER}}/myapp:${{ github.sha }}
        docker push ${{secrets.ACR_LOGIN_SERVER}}/myapp:${{ github.sha }}    

    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.appName}}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: ${{secrets.ACR_LOGIN_SERVER}}/myapp:${{ github.sha }}